# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_api', '0002_bookstoreitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookStoreItem',
            new_name='Books',
        ),
    ]
